version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=dockerx;Username=postgres;Password=postgres
      - AWS__Region=us-east-1
      - AWS__BucketName=dockerx-media
    depends_on:
      - db

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:80
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=dockerx
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 