version: '3.8'

services:
  test-db:
    image: postgres:16
    environment:
      POSTGRES_DB: dockerx_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"  # Using different port to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d dockerx_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data: 