version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dockerx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  upload:
    build:
      context: .
      dockerfile: src/Upload/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=dockerx;Username=postgres;Password=postgres
      - Storage__Provider=local
      - Storage__Local__BasePath=/app/uploads
    ports:
      - "5002:5002"
    volumes:
      - upload_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  media:
    build:
      context: .
      dockerfile: src/Media/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=dockerx;Username=postgres;Password=postgres
    ports:
      - "5003:5003"
    volumes:
      - upload_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  upload_data: 